stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew test

docker-build:
  stage: deploy
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE