version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: flags_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fts-app-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fts-app-network

  app:
    image: ftsapp:latest # Название вашего образа
    container_name: ftsapp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/featuredb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - fts-app-network

volumes:
  postgres-data:
  redis-data:

networks:
  fts-app-network:
    driver: bridge