version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: featuredb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  feature-toggle-service:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"