spring:
  application:
    name: feature-toggle-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/featuredb
    username: user
    password: password
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml